export const CREATE_PRODUCT_TYPE = "CREATE_PRODUCT_TYPE";
export const UPDATE_PRODUCT_TYPE = "UPDATE_PRODUCT_TYPE";
export const DELETE_PRODUCT_TYPE = "DELETE_PRODUCT_TYPE";
export const FETCH_PRODUCT_TYPES = "FETCH_PRODUCT_TYPES";